config/routes.rb
KoyService::Application.routes.draw do

  get "user/index"

  get "user/new"

  get "user/update"

  get "user/edit"

  get "user/login"

  match "user/delete" => "user#destroy"
  match "user/create" => "user#create"

  match "logout" => "user#logout", :as => :logout
  match "login" => "user#login", :as => :login

  root :to => 'user#login'

end

app/models/user.rb
require 'bcrypt'
class User < ActiveRecord::Base
  include BCrypt
  attr_accessible  :username

  validates :username, presence: true, uniqueness: true
  validates :password, presence:true, :confirmation => true
  validates :password_confirmation, :presence => true

  def password
    if not password_hash.nil?
      @password ||= Password.new(password_hash)
    else
      nil
    end
  end

  def password=(new_password)
    if not new_password.blank?
      @password = Password.create(new_password)
      self.password_hash = @password
    else
      self.password_hash = nil
    end
  end


  def is_admin?
    self.admin
  end
  
  def set_admin=(admin)
    self.admin = admin
  end



  def self.authenticate(username, password)
    user = find_by_username(username)

    if not user.nil? and user and user.password == password
      user 
    else
      false
    end
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :check_user, :except => [:login]



  private

  def check_user
    if session.blank? or session[:active_user].blank? 
      redirect_to root_path
    else
      @active_user = User.find(session[:active_user])
    end
  end



end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
    if @active_user.is_admin?
      @users = User.page(params[:page])
      render "index_admin"
    else
      render "index"
    end
  end

  def new
    @user = User.new
  end

  def create
 
    @user = User.new(:username => params[:user][:username])
    @user.password = params[:user][:password]
    @user.password_confirmation = params[:user][:password_confirmation]

    if @user.save
      flash[:success] = "User telah berhasil dibuat"
      redirect_to :action => "index"
    else
      render :action => "new"
    end

  end

  def update
  end

  def edit
  end

  def destroy
    if request.post? &&
      if @active_user.is_admin? 

        User.destroy(params[:id])
        flash[:notice] = "User telah dihapus"

      else
        flash[:notice] = "Anda bukan admin"
      end
    else
      flash[:error] = "Ada Error"
    end

    redirect_to :action => "index"
  end

  def logout
    session[:active_user] = nil

    flash[:notice] = "Anda telah berhasil logout"

    redirect_to root_path
  end

  def login

    if request.post?

      if @user = User.authenticate(params[:username], params[:password])
        session[:active_user] = @user.id
        redirect_to :action => "index"
      else
        flash[:error] = "Maaf, Password anda salah"
        redirect_to root_path
      end

    end

  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>KoyService123</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <div class="row">
      <div class="span3 offset9">
        <% if @active_user %>
          Hi <%= @active_user.username + (@active_user.is_admin? ? "[admin]" : "" ) %>, 
          &nbsp;&nbsp;
          <%= link_to "logout", logout_path, :class => "btn btn-danger btn-large", :id=>"logout" %>
        <% end %>
      </div>
    </div>
    <% flash.each do | type, message | %>
      <div class="alert <%= (type=="success") ? "alert-success" : "" %>">
        <button class="close" data-dismiss="alert">X</button>
        <%= message %>
      </div>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/user/_form.html.haml
= form_for @user, :url => {:action => zone } do |f|
  
  .row
    .span6.offset3
      -if @user.errors.any?
        #error_explanation
          %h2= "Ada #{@user.errors.count} yang salah"
          %ul
            - @user.errors.full_messages.each do |em|
              %li = em



  .row
    .span6.offset3
      .field
        = f.label :username
        = f.text_field :username

  .row
    .span6.offset3
      .field
        = f.label :password
        = f.text_field :password

  .row
    .span6.offset3
      .field
        = f.label :password
        = f.text_field :password_confirmation

  .row
    .span6.offset3
      .field
        = f.submit "Buat User", :class => "btn btn-large btn-primary", :id=>"create_user"
        &nbsp;&nbsp;&nbsp;&nbsp;
        = link_to "Batal", user_index_path, :class=> "btn btn-large btn-danger" 

app/views/user/create.html.haml
%h1 User#create
%p Find me in app/views/user/create.html.haml

app/views/user/edit.html.haml
%h1 User#edit
%p Find me in app/views/user/edit.html.haml

app/views/user/index.html.haml
%h1 User#index
%p Find me in app/views/user/index.html.haml

app/views/user/index_admin.html.haml
.row
  .span12.center
    %h1
      Daftar User
%br
%hr
.row
  .span2.offset10
    = link_to "User Baru", user_new_path, :class=>"btn btn-large btn-primary", :id=>"new_user"
.row
  .span8.offset2
    = will_paginate @users
    %table.table.table-bordered#user-table
      %thead
        %th
          Username
        %th
          Admin ?
        %th
      %tbody
        -@users.each do |user|
          %tr
            %td
              = user.username
            %td
              - if user.is_admin?
                .myIcon.ok
              -else
                .myIcon.no

app/views/user/login.html.haml
.row
  .span12.center
    Login
%br
%br
.row
  =form_tag("/login", :method => :post)
  .span4.offset4
    %table
      %tr
        %td
          =label_tag "username", "Username"
        %td
          = text_field_tag "username", "", :placeholder=>"Username"
      %tr
        %td
          =label_tag "password", "Password"
        %td
          = password_field_tag "password", ""
      %tr
        %td
          &nbsp;
        %td
          = submit_tag "login", :id=>"login", :class=>"login"
    

app/views/user/new.html.haml
%h1 Buat User baru

= render :partial => "form", :locals => {:zone => "create"}

app/views/user/update.html.haml
%h1 User#update
%p Find me in app/views/user/update.html.haml